#!/bin/sh

code --install-extension ms-azuretools.vscode-docker
code --install-extension eamodio.gitlens
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ipedrazas.kubernetes-snippets
code --install-extension ms-python.python
code --install-extension mauve.terraform
code --install-extension vscode-icons-team.vscode-icons
code --install-extension redhat.vscode-yaml
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension ms-vscode.csharp
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension hookyqr.beautify 
code --install-extension redhat.vscode-yaml
code --install-extension WakaTime.vscode-wakatime
code --install-extension bierner.markdown-mermaid
code --install-extension bierner.markdown-preview-github-styles
code --install-extension christian-kohler.path-intellisense
code --install-extension esbenp.prettier-vscode
code --install-extension donjayamanne.githistory
code --install-extension humao.rest-client
code --install-extension tht13.html-preview-vscode
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension ms-vscode.go
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension davidanson.vscode-markdownlint
code --install-extension oderwat.indent-rainbow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh-explorer
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
